import csv
import json
from types import SimpleNamespace

import casadi as ca
import numpy as np
import pytest
import cocofest.optimization.rho_retrospective_validation as retrospective

from cocofest.optimization.rho_retrospective_validation import (
    _forecast_outcome_audit,
    build_rho_retrospective_validation_report,
    write_rho_retrospective_validation,
)
from cocofest.optimization.rho_rollout_adapter import select_certified_rho_cycle


MUSCLES = ("m1", "m2")


class _ReducedDynamics:
    muscle_names = MUSCLES
    muscle_geometry = object()
    kinematics = SimpleNamespace(direction=-1)

    @staticmethod
    def muscle_relationships(theta, omega):
        assert np.isfinite(theta) and np.isfinite(omega)
        return np.array([0.90, 0.95]), np.array([1.0, 0.98]), np.array([0.02, 0.01])


def _models():
    return [
        SimpleNamespace(
            muscle_name=name,
            a_scale=4920.0 + 100.0 * index,
            tau1_rest=0.060601,
            km_rest=0.137,
            alpha_a=-0.04,
            alpha_tau1=2.1e-6,
            alpha_km=1.9e-6,
            tau_fat=127.0,
            tau2=0.001,
            pd0=0.000131405,
            pdt=0.000194138,
        )
        for index, name in enumerate(MUSCLES)
    ]


def _write_archive(
    path,
    *,
    cycles=8,
    force_scale=1.0,
    invalid_target=None,
    shifted_policy_cycle=None,
    shifted_policy_delta=0.0,
):
    stimulations = 6
    degree = 3
    points = np.asarray(ca.collocation_points(degree, "radau"))
    times = [0.0]
    for interval in range(cycles * stimulations):
        times.extend((interval + points) / stimulations)
        times.append((interval + 1.0) / stimulations)
    times = np.asarray(times)
    local_time = np.mod(times, 1.0)
    payload = {
        "states__theta": (-2.0 * np.pi * times)[None, :],
        "states__omega": np.full((1, times.size), -2.0 * np.pi),
    }
    for index, name in enumerate(MUSCLES):
        payload[f"states__F_{name}"] = (
            force_scale
            * (8.0 + index + (1.0 + 0.2 * index) * np.cos(2.0 * np.pi * local_time))
        )[None, :]
        payload[f"states__Cn_{name}"] = (
            0.40 + 0.02 * np.sin(2.0 * np.pi * local_time)
        )[None, :]
        # A known observed trend makes endpoint comparison unambiguous.
        payload[f"states__A_{name}"] = (
            4800.0 + 100.0 * index - (2.0 + index) * times
        )[None, :]
        payload[f"states__Tau1_{name}"] = (0.065 + 1e-5 * times)[None, :]
        payload[f"states__Km_{name}"] = (0.145 + 2e-5 * times)[None, :]
        pulse_widths = np.full(cycles * stimulations, 0.0003)
        if invalid_target is not None:
            first = invalid_target * stimulations
            pulse_widths[first] = 0.0007
        if shifted_policy_cycle is not None:
            first = shifted_policy_cycle * stimulations
            pulse_widths[first : first + stimulations] += shifted_policy_delta
        payload[f"controls__last_pulse_width_{name}"] = pulse_widths[None, :]
    metadata = {
        "schema": "test-rho",
        "producer_mode": "receding_horizon_concatenation",
        "cycles_per_window": cycles,
        "stimulations_per_cycle": stimulations,
        "producer_collocation_degree": degree,
        "producer_collocation_method": "radau",
        "cycle_duration_s": 1.0,
        "model_formulation": "periodic_node",
        "pulse_width_maximum_s": 0.0006,
        "activate_force_length_relationship": True,
        "activate_force_velocity_relationship": True,
        "activate_passive_force_relationship": True,
        "terminal_wheel_q_slack": 1e-6,
    }
    payload["metadata__json"] = np.asarray(json.dumps(metadata))
    np.savez(path, **payload)


def _build(source, reduced, **kwargs):
    adapter_options = {
        "force_harmonics": 2,
        "cn_harmonics": 2,
        "kinematic_harmonics": 2,
        # Synthetic F is prescribed analytically rather than generated by
        # the Ding ODE; dedicated adapter tests cover these independent gates.
        "collocation_force_ode_tolerance_n_per_s": 1e9,
        "midpoint_force_ode_tolerance_n_per_s": 1e9,
        "midpoint_pulse_width_error_tolerance_s": 1.0,
        "muscle_models": _models(),
        "reduced_dynamics": _ReducedDynamics(),
    }
    adapter_options.update(kwargs.pop("adapter_options", {}))
    scientific_criteria = kwargs.pop(
        "scientific_criteria",
        {
            "minimum_valid_anchors_per_horizon": 1,
            "maximum_A_rest_normalized_rmse": 10.0,
            "maximum_Tau1_rest_normalized_rmse": 10.0,
            "maximum_Km_rest_normalized_rmse": 10.0,
            "maximum_utilization_rmse": 10.0,
            "maximum_policy_drift_normalized_pw_rmse": 10.0,
            "maximum_policy_drift_normalized_pw_p95": 10.0,
            "minimum_critical_muscle_match_fraction": 0.0,
        },
    )
    return build_rho_retrospective_validation_report(
        source,
        reduced,
        adapter_options=adapter_options,
        scientific_criteria=scientific_criteria,
        **kwargs,
    )


def test_explicit_cycle_selector_uses_requested_cycle(tmp_path):
    source = tmp_path / "rho.npz"
    _write_archive(source)

    selected, _ = select_certified_rho_cycle(source, cycle_index=3)

    assert selected.cycle_index == 3
    assert selected.start_column == 3 * 6 * 4
    assert selected.end_column == 4 * 6 * 4
    assert selected.states["theta"][selected.end_column] == -8.0 * np.pi

    with pytest.raises(ValueError, match="outside the declared range"):
        select_certified_rho_cycle(source, cycle_index=8)
    with pytest.raises(ValueError, match="must be an integer"):
        select_certified_rho_cycle(source, cycle_index=1.5)


def test_rho_only_retrospective_builds_auditable_state_and_recruitment_errors(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source)
    reduced.write_bytes(b"reduced-test-profile")

    report = _build(
        source,
        reduced,
        anchors=(1,),
        horizons=(2, 5),
        saturation_threshold=0.9,
    )

    assert report["processing_status"] == "complete"
    assert report["scientific_validation_status"] == "passed"
    assert report["data_policy"] == "rho_only_no_full_horizon_data"
    assert report["selection"]["indexing"] == "zero_based; forecast origin=end(k); target=end(k+H)"
    assert report["source"]["sha256"]
    assert report["reduced_profile"]["sha256"]
    assert report["record_counts"] == {"valid": 2}
    assert report["configuration"]["saturation_threshold"] == 0.9
    assert "scientific_criteria" in report["configuration"]
    assert [row["horizon_cycles"] for row in report["aggregate_metrics_by_horizon"]] == [2, 5]
    assert report["aggregate_metrics_by_horizon"][0]["metrics"]["valid_anchor_count"] == 1
    assert np.isfinite(
        report["aggregate_metrics_by_horizon"][0]["metrics"]["slow_state_errors"]["A"]["rmse"]
    )
    for record in report["records"]:
        assert record["status"] == "valid"
        assert record["target_cycle_index"] == 1 + record["horizon_cycles"]
        metrics = record["metrics"]
        assert set(metrics["slow_state_errors"]) == {"A", "Tau1", "Km"}
        assert len(metrics["slow_state_errors"]["A"]["per_muscle"]) == 2
        assert np.isfinite(metrics["slow_state_errors"]["A"]["rmse"])
        assert np.isfinite(metrics["capacity_ratio"]["minimum_error"])
        assert np.isfinite(metrics["recruitment"]["maximum_utilization_error"])
        assert isinstance(metrics["recruitment"]["critical_muscle_match"], bool)
        assert metrics["observed_policy_drift"]["worst_over_horizon"]["rmse"] == pytest.approx(
            0.0
        )
        assert metrics["observed_policy_drift"]["worst_over_horizon"][
            "p95_absolute"
        ] == pytest.approx(0.0)
        assert len(metrics["observed_policy_drift"]["per_cycle"]) == record["horizon_cycles"]
    horizon_two = report["records"][0]
    assert horizon_two["target_cycle_index"] == 3
    assert horizon_two["metrics"]["slow_state_errors"]["A"]["per_muscle"][0][
        "observed"
    ] == pytest.approx(4792.0)
    expected_utilization = -np.expm1(-(0.0003 - 0.000131405) / 0.000194138) / -np.expm1(
        -(0.0006 - 0.000131405) / 0.000194138
    )
    assert horizon_two["metrics"]["recruitment"][
        "maximum_utilization_observed"
    ] == pytest.approx(expected_utilization)


def test_unavailable_target_is_censored_without_metrics(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source)
    reduced.write_bytes(b"reduced-test-profile")

    report = _build(source, reduced, anchors=(6,), horizons=(1, 2, 5))

    assert report["processing_status"] == "complete_with_censoring"
    by_horizon = {record["horizon_cycles"]: record for record in report["records"]}
    assert by_horizon[1]["status"] == "valid"
    assert by_horizon[2]["status"] == "censored_target_unavailable"
    assert by_horizon[2]["metrics"] is None
    assert by_horizon[5]["censoring"]["last_available_cycle_index"] == 7
    assert report["aggregate_metrics_by_horizon"][1]["metrics"] is None


def test_requested_anchor_beyond_partial_archive_is_explicitly_censored(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source)
    reduced.write_bytes(b"reduced-test-profile")

    report = _build(source, reduced, anchors=(8,), horizons=(2, 5))

    assert report["processing_status"] == "fully_censored"
    assert report["scientific_validation_status"] == "not_evaluable"
    assert report["record_counts"] == {"censored_anchor_unavailable": 2}
    assert all(record["metrics"] is None for record in report["records"])


def test_failed_source_policy_gate_never_emits_comparison_metrics(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source, force_scale=30.0)
    reduced.write_bytes(b"reduced-test-profile")

    report = _build(
        source,
        reduced,
        anchors=(1,),
        horizons=(2,),
        adapter_options={"midpoint_force_ode_tolerance_n_per_s": 1e-8},
    )

    assert report["processing_status"] == "no_valid_comparisons"
    assert report["scientific_validation_status"] == "not_evaluable"
    record = report["records"][0]
    assert record["status"] == "invalid_anchor_policy"
    assert record["gate"]["adapter_status"] == "midpoint_approximation_out_of_tolerance"
    assert record["gate"]["adapted_policy_fidelity"]["passed"] is False
    assert record["gate"]["source_transcription"]["passed"] is True
    assert record["metrics"] is None


def test_invalid_target_pulse_width_is_not_clipped_or_scored(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source, invalid_target=3)
    reduced.write_bytes(b"reduced-test-profile")

    report = _build(source, reduced, anchors=(1,), horizons=(2,))

    record = report["records"][0]
    assert record["status"] == "invalid_observed_policy_path"
    assert record["invalid_observed_cycle_index"] == 3
    assert record["observed_cycle_audit"]["reason"] == "observed_pulse_width_out_of_domain"
    assert record["observed_cycle_audit"]["domain_violations"][0]["pulse_width_s"] == 0.0007
    assert record["metrics"] is None


def test_policy_drift_and_tolerated_observed_bound_noise_are_auditable(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(
        source,
        shifted_policy_cycle=3,
        shifted_policy_delta=1e-5,
    )
    reduced.write_bytes(b"reduced-test-profile")

    report = _build(source, reduced, anchors=(1,), horizons=(2,))

    record = report["records"][0]
    assert record["status"] == "valid"
    expected = 1e-5 / (0.0006 - 0.000131405)
    drift = record["metrics"]["observed_policy_drift"]
    assert drift["worst_over_horizon"]["rmse"] == pytest.approx(expected)
    assert drift["worst_over_horizon"]["p95_absolute"] == pytest.approx(
        expected
    )
    assert len(drift["per_cycle"]) == 2
    assert record["observed_pulse_width_audits"]["path"][-1]["clipping_applied"] is False


def test_intermediate_policy_excursion_is_not_hidden_by_exact_final_return(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(
        source,
        shifted_policy_cycle=2,
        shifted_policy_delta=1e-5,
    )
    reduced.write_bytes(b"reduced-test-profile")
    threshold = 0.5 * 1e-5 / (0.0006 - 0.000131405)

    report = _build(
        source,
        reduced,
        anchors=(1,),
        horizons=(2,),
        scientific_criteria={
            "minimum_valid_anchors_per_horizon": 1,
            "maximum_A_rest_normalized_rmse": 10.0,
            "maximum_Tau1_rest_normalized_rmse": 10.0,
            "maximum_Km_rest_normalized_rmse": 10.0,
            "maximum_utilization_rmse": 10.0,
            "maximum_policy_drift_normalized_pw_rmse": threshold,
            "maximum_policy_drift_normalized_pw_p95": 10.0,
            "minimum_critical_muscle_match_fraction": 0.0,
        },
    )

    drift = report["records"][0]["metrics"]["observed_policy_drift"]
    assert drift["per_cycle"][0]["rmse"] > 0.0
    assert drift["per_cycle"][1]["rmse"] == pytest.approx(0.0)
    assert drift["worst_over_horizon"]["rmse_cycle_index"] == 2
    assert drift["worst_over_horizon"]["rmse"] > threshold
    assert report["processing_status"] == "complete"
    assert report["scientific_validation_status"] == "failed"


def test_solver_scale_observed_pw_bound_excursion_is_accepted_but_never_clipped(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source)
    with np.load(source, allow_pickle=False) as archive:
        payload = {key: np.asarray(archive[key]).copy() for key in archive.files}
    payload["controls__last_pulse_width_m1"][0, 3 * 6] = 0.0006 + 5e-11
    np.savez(source, **payload)
    reduced.write_bytes(b"reduced-test-profile")

    report = _build(
        source,
        reduced,
        anchors=(1,),
        horizons=(2,),
        observed_pulse_width_tolerance_s=1e-10,
    )

    record = report["records"][0]
    assert record["status"] == "valid"
    audit = record["observed_pulse_width_audits"]["path"][-1]
    assert audit["tolerated_bound_excursion_count"] == 1
    assert audit["tolerated_bound_excursions"][0]["signed_bound_excursion_s"] == pytest.approx(
        5e-11
    )
    assert audit["clipping_applied"] is False

    rejected = _build(
        source,
        reduced,
        anchors=(1,),
        horizons=(2,),
        observed_pulse_width_tolerance_s=1e-12,
    )
    assert rejected["records"][0]["status"] == "invalid_observed_policy_path"
    assert rejected["records"][0]["metrics"] is None


def test_forecast_audit_rejects_nonfinite_utilization_and_nonphysiological_state():
    parameters = [
        {
            "muscle": "m1",
            "A_rest": 100.0,
            "Tau1_rest": 0.05,
            "Km_rest": 0.1,
        }
    ]
    forecast = {
        "feasible": True,
        "final_slow_states": [[101.0, 0.05, 0.1]],
        "last_cycle_recruitment": {
            "maximum_finite_utilization": None,
            "saturated_sample_fraction": None,
            "finite_sample_count": 0,
            "critical_location": None,
        },
    }

    audit = _forecast_outcome_audit(
        forecast,
        model_parameters=parameters,
        expected_utilization_samples=6,
    )

    assert audit["valid"] is False
    assert {reason["code"] for reason in audit["reasons"]} == {
        "non_physiological_final_slow_state",
        "non_finite_or_incomplete_predicted_utilization",
    }


def test_runner_never_scores_an_infeasible_forecast(monkeypatch, tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source)
    reduced.write_bytes(b"reduced-test-profile")
    actual_builder = retrospective.build_rho_endurance_rollout_report

    def infeasible_builder(*args, **kwargs):
        report = actual_builder(*args, **kwargs)
        for horizon in report["horizons"]:
            horizon["feasible"] = False
            horizon["first_failure"] = {"status": "pulse_width_limit_exceeded"}
            horizon["last_cycle_recruitment"]["maximum_finite_utilization"] = None
            horizon["last_cycle_recruitment"]["saturated_sample_fraction"] = None
            horizon["last_cycle_recruitment"]["finite_sample_count"] = 0
            horizon["last_cycle_recruitment"]["critical_location"] = None
        return report

    monkeypatch.setattr(
        retrospective,
        "build_rho_endurance_rollout_report",
        infeasible_builder,
    )

    report = _build(source, reduced, anchors=(1,), horizons=(2,))

    record = report["records"][0]
    assert record["status"] == "invalid_forecast_outcome"
    assert record["metrics"] is None
    assert any(
        reason["code"] == "physiologically_infeasible_recruitment_forecast"
        for reason in record["forecast_audit"]["reasons"]
    )
    assert any(
        reason["code"] == "non_finite_or_incomplete_predicted_utilization"
        for reason in record["forecast_audit"]["reasons"]
    )


def test_scientific_failure_is_separate_from_successful_processing(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source)
    reduced.write_bytes(b"reduced-test-profile")

    report = _build(
        source,
        reduced,
        anchors=(1,),
        horizons=(2,),
        scientific_criteria={"minimum_valid_anchors_per_horizon": 2},
    )

    assert report["processing_status"] == "complete"
    assert report["scientific_validation_status"] == "failed"
    horizon = report["aggregate_metrics_by_horizon"][0]
    assert horizon["processing_status"] == "complete"
    assert horizon["scientific_validation_status"] == "failed"
    sample_count = next(
        row
        for row in horizon["criteria_results"]
        if row["criterion"] == "minimum_valid_anchors_per_horizon"
    )
    assert sample_count["passed"] is False


def test_json_csv_writer_leaves_invalid_metric_cells_empty(tmp_path):
    source = tmp_path / "rho.npz"
    reduced = tmp_path / "reduced.npz"
    _write_archive(source)
    reduced.write_bytes(b"reduced-test-profile")
    report = _build(source, reduced, anchors=(6,), horizons=(1, 2))
    json_output = tmp_path / "report.json"
    csv_output = tmp_path / "report.csv"

    write_rho_retrospective_validation(json_output, csv_output, report)

    loaded = json.loads(json_output.read_text())
    assert loaded == report
    assert "NaN" not in json_output.read_text()
    with csv_output.open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    assert len(rows) == 2
    assert rows[0]["status"] == "valid"
    assert rows[0]["A_rmse"]
    assert rows[1]["status"] == "censored_target_unavailable"
    assert rows[1]["A_rmse"] == ""
